language: cpp
os: linux
compiler: gcc
dist: xenial
cache: ccache
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - gcc
      - cmake
      - ninja-build
      - clang-8
      - llvm-8
      - llvm-8-dev
      - bison
before_script:
  - ulimit -c unlimited
  - ccache -s -z
script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - ninja
after_script:
  - ccache -s
